name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "src,requirements.txt,main.py,components.py"
          target: "/home/deploy/socket-demo"

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/deploy/socket-demo
            source venv/bin/activate
            pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt --default-timeout=60
            sudo systemctl restart socket-demo.service
            sleep 5
            sudo systemctl is-active --quiet socket-demo.service && echo "Service is running" || echo "Service failed to start"